export const UNITS = [
    { unitID: 1, type: 'g' },
    { unitID: 2, type: 'ml' },
    { unitID: 3, type: 'unité' },
    { unitID: 4, type: 'kg' },
    { unitID: 5, type: 'mg' },
    { unitID: 6, type: 'cL' },
    { unitID: 7, type: 'L' },
    { unitID: 8, type: 'pièce' },
    { unitID: 9, type: 'tranche' },
    { unitID: 10, type: 'gousse' },
    { unitID: 11, type: 'branche' },
    { unitID: 12, type: 'feuille' },
    { unitID: 13, type: 'pincée' },
    { unitID: 14, type: 'poignée' },
    { unitID: 15, type: 'c. à c.' },
    { unitID: 16, type: 'c. à s.' },
    { unitID: 17, type: 'sachet' },
    { unitID: 18, type: 'bouquet' },
]